### ISSUE TITLE
Publishing Guidelines.

### ISSUE THREAD

**Issue by Eiyeron** [Wifsimster/datagamer#1]
Hi. I don't know if it's the right place to talk about the current online version but here are some precisions I think these should be cleared for a better future : 
- Multiples games have different names abroad the different release zones. Of course, japanese ones are the most frequent (_ahem_ Pocket Monsters became Pokémons out of Japan) but some changes are too done between the PAL and NTSC zones (Contra became Probobector in PAL IIRC). Changes should be made to support naming for different regions or making aliases and redirect to a specific version (for instance US NTSC).
- Same for release dates. Different regions and different release dates.
- One user, knowing the month but not finding the exact date could set only the month/year and not the day.
- What about early access/constant developpment games or physical only games? Should we put the first beta release date or wait until the 1.0 is out to write it?
- Covers : For games not having a physical cover, what kind of picture should we use? One coming from a press kit? An official one? A well known one?
- Something that's frontend independant but still related : what's the current rules to upload a picture as cover? I'm still wondering how I could support them with the Haxe frontend.

**Comment by Wifsimster** [comment]
Hi, sorry for the delay.

Please comment on this repo : https://github.com/Wifsimster/datagamer-api-v2
This is the right one ;)

datagamer is currently a local web app using Datagamer API v2 for video games managment :)
